sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    ‐ hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: main
    local_dir: public
    repo: TLpigff/TLpigff.github.io
    fqdn: <custom-domain-if-needed>
    target_branch: main
    email: 704974976@qq.com
    name: TLpigff
